version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/rust.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

  db:
    image: "postgres:9"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    tty: true

  app:
    build:
      context: .
      dockerfile: ./docker/nextjs.Dockerfile
    volumes:
      - ./app:/app 
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm install && npm run dev"
    tty: true

volumes:
  cargo-cache:
  target-cache:
  pgdata: {}