import Head from "next/head";
import SignUpPage from "../src/components/sign-up";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUpPage />
    </div>
  );
}
